Repository Railcraft/Railcraft, pull requests merged in 2018-05, with the labels that each got.

#1400 Work on RC 1.12.x
  src/main/java/mods/railcraft/common/worldgen/GenTools.java
  src/main/java/mods/railcraft/common/worldgen/Generator.java
  version/gradle.properties
Labels: alpha, bug, high priority

#1401 use current rf api
  build.gradle
  src/api/java/cofh/README.md
  src/api/java/cofh/api/CoFHAPIProps.java
  src/api/java/cofh/api/LICENSE - LGPLv3.txt
  src/api/java/cofh/api/energy/EnergyStorage.java
  src/api/java/cofh/api/energy/IEnergyConnection.java
  src/api/java/cofh/api/energy/IEnergyContainerItem.java
  src/api/java/cofh/api/energy/IEnergyHandler.java
  src/api/java/cofh/api/energy/IEnergyProvider.java
  src/api/java/cofh/api/energy/IEnergyReceiver.java
  src/api/java/cofh/api/energy/IEnergyStorage.java
  src/api/java/cofh/api/energy/ItemEnergyContainer.java
  src/api/java/cofh/api/energy/TileEnergyHandler.java
  src/api/java/cofh/api/energy/package-info.java
  src/api/java/cofh/api/package-info.java
  src/main/java/mods/railcraft/common/blocks/machine/manipulator/TileRFLoader.java
  src/main/java/mods/railcraft/common/blocks/machine/manipulator/TileRFManipulator.java
  src/main/java/mods/railcraft/common/blocks/machine/manipulator/TileRFUnloader.java
  src/main/java/mods/railcraft/common/blocks/single/TileEngine.java
  src/main/java/mods/railcraft/common/blocks/single/TileEngravingBench.java
  src/main/java/mods/railcraft/common/gui/widgets/RFEnergyIndicator.java
  src/main/java/mods/railcraft/common/plugins/rf/RedstoneFluxPlugin.java
  version/build.gradle
  version/gradle.properties
Labels: alpha, bug, high priority, mod compatibility, work in progress

#1333 Added bed cart
  extras/ide/inspections/net/minecraftforge/event/entity/player/annotations.xml
  src/main/java/mods/railcraft/client/core/SleepKeyHandler.java
  src/main/java/mods/railcraft/common/carts/EntityCartBed.java
  src/main/java/mods/railcraft/common/carts/ItemCartBed.java
  src/main/java/mods/railcraft/common/carts/RailcraftCarts.java
  src/main/java/mods/railcraft/common/modules/ModuleExtras.java
  src/main/java/mods/railcraft/common/util/misc/EntityIDs.java
  src/main/java/mods/railcraft/common/util/network/PacketKeyPress.java
  src/main/resources/assets/railcraft/models/item/cart_bed.json
Labels: carts, enhancement, low priority

#1406 Fixes for 1.12 Branch
  src/main/java/mods/railcraft/client/core/SleepKeyHandler.java
  src/main/java/mods/railcraft/common/blocks/aesthetics/post/ItemPost.java
  src/main/java/mods/railcraft/common/blocks/charge/ItemChargeBattery.java
  src/main/java/mods/railcraft/common/blocks/machine/worldspike/ItemWorldspike.java
  src/main/java/mods/railcraft/common/carts/EntityCartBed.java
  src/main/java/mods/railcraft/common/carts/ItemCart.java
  src/main/java/mods/railcraft/common/carts/ItemCartWorldspike.java
  src/main/java/mods/railcraft/common/carts/ItemLocomotive.java
  src/main/java/mods/railcraft/common/items/IRailcraftItem.java
  src/main/java/mods/railcraft/common/items/ItemCrowbarSeasons.java
  src/main/java/mods/railcraft/common/items/ItemFilterBeeGenome.java
  src/main/java/mods/railcraft/common/items/ItemFilterOreDictionary.java
  src/main/java/mods/railcraft/common/items/ItemFilterSimple.java
  src/main/java/mods/railcraft/common/items/ItemGoggles.java
  src/main/java/mods/railcraft/common/items/ItemNotepad.java
  src/main/java/mods/railcraft/common/items/ItemOveralls.java
  src/main/java/mods/railcraft/common/items/firestone/ItemFirestoneRefined.java
Labels: alpha

#1389 Water tank item and block
  src/main/java/mods/railcraft/common/blocks/RailcraftBlocks.java
  src/main/java/mods/railcraft/common/blocks/multi/BlockTankWater.java
  src/main/java/mods/railcraft/common/blocks/multi/ItemTankWater.java
  src/main/java/mods/railcraft/common/blocks/multi/TileTankWater.java
  src/main/java/mods/railcraft/common/modules/ModuleFactory.java
  src/main/resources/assets/railcraft/blockstates/tank_water.json
Labels: high priority, machines and multiblocks
